# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby


trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: '~> 2.7'
      addToPath: true

  - script: |
      gem install bundler
      bundle install
    displayName: 'Install dependencies'

  - script: |
      curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      sudo apt-get install -y nodejs
      bundle exec rake db:migrate RAILS_ENV=test
      RAILS_ENV=test bundle exec rake assets:precompile
      bundle exec rspec
    displayName: 'Run RSpec tests with asset precompilation'

