# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby


trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      sudo apt-get update
      sudo apt-get install -y gnupg2 curl
      gpg2 --keyserver hkp://keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
      curl -sSL https://rvm.io/mpapis.asc | gpg --import -
      curl -sSL https://get.rvm.io | bash -s stable
      source ~/.rvm/scripts/rvm
      rvm install 2.7.7
      gem install bundler
      bundle install
    displayName: 'Install Ruby and dependencies'
  - script: |
      curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      sudo apt-get install -y nodejs
      bash -lc "bundle exec rails db:create db:migrate RAILS_ENV=test"
      bash -lc "RAILS_ENV=test bundle exec rails assets:precompile"
      bash -lc "bundle exec rspec"
    displayName: 'Run RSpec tests with asset precompilation'

